name: Cement Design Magyarország
favicon: null
layout_spectrum: 0.21655
typography_spectrum: 0.77588
title: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FBFFF7'
    - '#231C24'
    - '#4D434E'
    - '#ACAAD9'
    - '#B27B5E'
  brandStrength: 0
  lightness: 0.7574468
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
