title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#FBFFF7'
    - '#231C24'
    - '#4D434E'
    - '#ACAAD9'
    - '#B27B5E'
  lightness: 0.4553191
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Cement Design Magyarország
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9638298
layout_spectrum: 0
