name: Cement Design Magyarország
favicon: null
layout_spectrum: 0.85004
typography_spectrum: 0.17759
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfefd'
    - '#090611'
    - '#bbac8b'
    - '#b57b3b'
    - '#822f11'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
