name: Cement Design Magyarország
favicon: null
layout_spectrum: 0.3032
typography_spectrum: 0.17759
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0e0b'
    - '#1b1b19'
    - '#333230'
    - '#bb2a00'
    - '#c01c00'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.8961266644764692
  rhythmicContrast: 0.21417560521513224
purpose: []
