name: cementdesign
favicon: null
layout_spectrum: 0.16334993485361338
typography_spectrum: 0.48476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151513'
    - '#7d7666'
    - '#f5f4f2'
    - '#cdc1a9'
    - '#a69d8e'
  brandStrength: 0.9792989881243557
  lightness: 0.125
  saturation: 0.8961266644764692
  rhythmicContrast: 0.21417560521513224
purpose: []
